apiVersion: v1
kind: Service
metadata:
  name: kandpal-frontend-service
  namespace: kandpal-transport
spec:
  type: NodePort
  selector:
    app: kandpal-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
      